server:
  port: 8081

spring:
  cloud:
    config:
      import-check:
        enabled: false
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka